import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState } from "react";
import { HeaderComponent } from "../../components/HeaderComponent/HeaderComponent";
import { SidebarComponent } from "../../components/SidebarComponent/SidebarComponent";
import { UserModalComponent } from "../../components/UserModalComponent/UserModalComponent";
import { StyledAppShadowOverlay, StyledInnerWrapper, StyledWrapper } from "./Main.styles";
import { Layout } from "./Main.types";

export const MainLayout = ({children}: Layout) => {
    const [isMenuVisible, setIsMenuVisible] = useState(false);
    const [isUserModalVisible, setIsUserModalVisible] = useState(false)
    const {data:session,status} = useSession();

   

  return (
    <>
    <StyledAppShadowOverlay showMenu={isMenuVisible} onClick={() => setIsMenuVisible(false)}
        />
    <StyledWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent session={session} onClick={()=>setIsUserModalVisible(!isUserModalVisible)}/>

      <UserModalComponent session={session} isUserModalVisible={isUserModalVisible}/>

      <SidebarComponent onClick={() => setIsMenuVisible(!isMenuVisible)} isMenuVisible={isMenuVisible}/>
      <StyledInnerWrapper>
         {children}
      </StyledInnerWrapper>
    </StyledWrapper>
    </>
  );
};
